 name: actions
 on: 
   push

 jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
  
   - name: git clone
     uses: actions/checkout@v1
     
   - name: build hello
     run: |
       cd hello_world_application
       cmake -B applications
       cmake --build applications --target hello_world
       ./applications/hello_world > hello.txt
       cat hello.txt
       cd ..

   - name: download_artifact 
     uses: actions/download-artifact@v3
     with:
       name: hello_world
       path: ./artifact
       
